### ISSUE TITLE
Device names in Rule editor

### ISSUE THREAD

**Issue by matthijsf** [treban/pimatic-tradfri#1]
The device names in the rules editor show the original Tradfri ID rather than a readable name when creating a rule based on the dim level of a lamp. A state based rule however does show the correct ID. I'm not sure if this is a pimatic or tradfri plugin limitation.

**Dimlevel based rule**
![screen shot 2017-06-08 at 09 31 03](https://user-images.githubusercontent.com/4282608/26917107-3d863b30-4c2d-11e7-9015-19045090bd0b.png)

**State based rule**
![screen shot 2017-06-08 at 09 32 54](https://user-images.githubusercontent.com/4282608/26917172-89622bb8-4c2d-11e7-8d66-79f7e45396d7.png)

**Comment by treban** [comment]
The inheritance class for the devices is the pimatic default dimmer,
and so also the action and predicate providers. 

In text mode the list shows in both cases names and IDs. 
In GUI Mode there is a difference.

**Comment by treban** [comment]
This is a pimatic core limitation.
