### ISSUE TITLE
TradfriSwitch.changeStateTo doesn't return Promise in all cases

### ISSUE THREAD

**Issue by michbeck100** [treban/pimatic-tradfri#12]
https://github.com/treban/pimatic-tradfri/blob/c129be85f9c2dbd6814344af348089d78fb5dcc3/tradfri.coffee#L469 won't return a Promise if the variable tradfriReady is false. But Implementations of changeStateTo in env.devices.SwitchActuator must always return a Promise. I guess this is why https://github.com/michbeck100/pimatic-hap/issues/75 happened.

I did not check the methods of the other devices. There might be more missing Promises.

**Comment by treban** [comment]
You're right. I will fix it.

**Comment by kloknibor** [comment]
Any progress on this :)?

**Comment by treban** [comment]
I was on holiday until yesterday. I will fix this until the weekend.

**Comment by michbeck100** [comment]
is this fixed, yet?

**Comment by treban** [comment]
I will release today or no later than tomorrow a new version

**Comment by treban** [comment]
This bug should be fixed with version 0.1.13

**Comment by michbeck100** [comment]
Works! issue can be closed
