### ISSUE TITLE
Dimmer device for groups

### ISSUE THREAD

**Issue by treban** [treban/pimatic-tradfri#13]
Feature request
https://forum.pimatic.org/topic/3075/new-pimatic-tradfri-plugin-ikea-smart-lights/66

**Comment by michbeck100** [comment]
Looks like moods are also supported on groups (https://github.com/ggravlingen/pytradfri/blob/master/pytradfri/group.py). Would be great if this enhancement could be extended 😉

**Comment by treban** [comment]
Moods are already implemented. 
Pimatic Device-Class: TradfriGroupScene
It's a button device. (also over Auto-Discovery)
Or do you mean something else?

**Comment by michbeck100** [comment]
I was expecting the same UI as with a single bulb. But maybe that’s not possible?

**Comment by treban** [comment]
This feature is now available with the new version 0.1.13
Groups are now also a dimming device.
