### ISSUE TITLE
No class for opal 1000lm

### ISSUE THREAD

**Issue by matthijsf** [treban/pimatic-tradfri#2]
When detecting the 1000lm opal (white only) bulb, by default no class is selected. By manually selecting Tradfri dimmer it works just fine however.
Debug output from console upon detection:

20:08:38.199 [pimatic] info: Device discovered: pimatic-tradfri : LIGHT: Baby Room - TRADFRI bulb E27 opal 1000lm

![screen shot 2017-06-08 at 20 03 52](https://user-images.githubusercontent.com/4282608/26943472-0554631e-4c86-11e7-89a8-f3c9913e6ddc.png)
![screen shot 2017-06-08 at 20 03 36](https://user-images.githubusercontent.com/4282608/26943474-07377fcc-4c86-11e7-8c6c-bb24ba2fbe58.png)

**Comment by treban** [comment]
The PlugIn should have a default device for unknown lights.

**Comment by treban** [comment]
FIXED with 0.1.8
- default device for unknow devices
- TRADFRI bulb E27 opal 1000lm now supported

**Comment by matthijsf** [comment]
I can confirm the Bulb is now discovered properly! Thanks, awesome stuff!
