### ISSUE TITLE
Unable to create action "set color temp" in rule

### ISSUE THREAD

**Issue by cklam2** [treban/pimatic-tradfri#24]
#### Pimatic version :
0.9.42

#### Plugin version : 
0.1.17

#### Problem / Feature :
Unable to create action ``set color temp`` in rule

#### Expected :
Expected color temp action to work like the set color rgb action. 

#### Notes
If I create a rule and enter "set color rgb" then pimatic will show the list of tradfri devices and after selecting a device it will show option ``to`` so I will end up in this action: ``set color rgb Living Room to #ff0000``and I can save this.

However if I do the same for action ``set color temp`` it won't pop up Tradfri devices. Instead it pops up ``the``. If I manually enter the entire action, ie ``set color temp Living Room to 80`` and save the rule then pimatic will show an error message:
``Could not find an provider that provides the next action of "set color temp Living Room (RGB) to 80".``

**Comment by treban** [comment]
i will check this

**Comment by FranzieR** [comment]
When you type "set color rgb" it will show "the" but when you type "set color temp" it will show the tradfri_ devices!!

**Comment by treban** [comment]
i think the problem is 
that the "set color temp" action is only possible for device type: "**TradfriDimmerTemp**" 
and the "set color rgb" action is only possible for device type: "**TradfriRGB**"

I will modify the "set color temp" action so that both actions are offered for RGB bulbs. 

@cklam2 you should have a rgb bulb ?
@FranzieR and you should have a temperature bulb ?

**Comment by cklam2** [comment]
@treban, thanks for the support. I indeed have a TradfriRGB bulb. In the UI I can control its color, dim level and hue (=blue-yellow).

**Comment by FranzieR** [comment]
@treban Thank you!
Sorry, what is a temperature bulb? Only shades of white?

**Comment by FranzieR** [comment]
After Reading again I understnd what you mean 😀. Yes I have a temp, no RGB, bulb 😀
I was searching in a rule a way to dim the light at startup to 50% but only found a way to change the temp. (...and turn on Lamp Bank links and set color temp Lamp bank links to 61....) How to change the dimming to 50%?

**Comment by treban** [comment]
Just:
dim Lamp Bank links to 50%

**Comment by cklam2** [comment]
Oh great, I didn't know that either, this action wasn't listed in the readme.md. Will try that tonight.

**Comment by treban** [comment]
Your welcome. 
The dim action is a default pimatic action for all light devices and not implement from this plugin. 
But I will make a hint in the readme.

**Comment by FranzieR** [comment]
Thanks #treban!

**Comment by cklam2** [comment]
I changed line 1019 to ``'TradfriDimmerTemp', 'TradfriRGB'`` in tradfri.coffee. After that, 'set color temp' works fine for TradfriRGB. Also the dim action works like a charm.

**Comment by treban** [comment]
Thank you for the hint. I will release a new version soon.

**Comment by cklam2** [comment]
Created pull request with changes that we discussed, see #25.

**Comment by cklam2** [comment]
Thanks for merging, closing now
