### ISSUE TITLE
Tradfri Hub version 1.9.27 // Bad Request

### ISSUE THREAD

**Issue by osxdoc** [treban/pimatic-tradfri#38]
#### Pimatic version :
0.9.54
Node.js version 10.16.3
OpenSSL version 1.1.1c

#### Plugin version : 
0.1.22

#### Problem :
Doesn't work with the Hub version 1.9.27, no error shown in logfiles only if I want turn on/off a bulb/panel Pimatic shows a "Bad Request" popup.
Actual state of the lighting doesn't shown up in Pimatic.

**Comment by treban** [comment]
i will check it. 
have you tried rebooting the tradfri gateway?

**Comment by osxdoc** [comment]
Yes, rebooted many times.
Maybe a conflict with Node.js version 10.16.3?

**Comment by treban** [comment]
node 10.x shouldn't be the problem. i am also use node10 with gateway version 1.9.27.
please try to remove identitiy and psk from the config. 
This will create a new session key.

**Comment by osxdoc** [comment]
Thats it!
Thanks, now it works after removing identity and psk and creating the new session key.

**Comment by treban** [comment]
you're welcome.
