### ISSUE TITLE
light gets automatic off when switched on

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-tradfri#5]
if a dimmer of a light is set to 0 from scene and i switch it in the frontend or via rule on, the light turns on and after 1 seconds it goes off.

if i switch the light to 10% and turn it off and on again, no problems

**Comment by treban** [comment]
I can't reproduce this error. 

This is the situation?: 
A scene turns one light on and the other one off. If i dim the off light on, it doesn't stay on. 

Please turn debug on and post the logging messages for these request.

**Comment by scobby** [comment]
Here is the log:

debug [pimatic-tradfri]: ON/OFF: 0, brightness: 1
23:30:25debug [pimatic-tradfri]: New device values received for kueche-2
23:30:25debug [pimatic-tradfri]: ON/OFF: 0, brightness: 0
23:30:25debug [pimatic-tradfri]: New device values received for kueche-2
23:30:25debug [pimatic-tradfri]: ON/OFF: 1, brightness: 0
23:30:25debug [pimatic-tradfri]: New device values received for kueche-2
23:30:25debug [pimatic-tradfri]: { state: 1, brightness: 0 }
23:30:25debug [pimatic-tradfri]: New value send to device

**Comment by scobby** [comment]
when in this state it always gets directly off. only when i change the dimmer, it operates normal again.

i defined a scene "off" where all lamps are at 0% (only option in tradfri app)

**Comment by treban** [comment]
I found a bug. But I don't know if it depends with this problem.
Can you post more log message ....beginning with the scene change And with the send messages

**Comment by treban** [comment]
Update 0.1.11 should fix the error. 
But i couldn't reproduce this problem. 
Please check it....

**Comment by treban** [comment]
Problem Fixed: ...
https://forum.pimatic.org/topic/3075/new-pimatic-tradfri-plugin-ikea-smart-lights/46

**Comment by treban** [comment]
If the error occurs again, I re-open the ticket again.
