### ISSUE TITLE
startup off pimatic failed with pimatic-tradfri

### ISSUE THREAD

**Issue by scobby** [treban/pimatic-tradfri#6]
13:34:38.399 [pimatic-mobile-frontend] info: packing static assets
13:34:39.774 [pimatic-mobile-frontend] info: packing static assets finished
13:34:39.781 [pimatic-mobile-frontend] info: rendering html
Unhandled rejection (<{"error":{"code":"ECONNRESET"},"option...>, no stack trace)
13:34:43.679 [pimatic] error: A uncaught exception occurred: TypeError: Cannot read property 'send' of null
13:34:43.679 [pimatic] error:>    at DtlsClientSocket.dgramSocket.once.send (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/node_modules/node-mbed-dtls/client_socket.js:63:22)
13:34:43.679 [pimatic] error:>    at RetrySend._send (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/retry_send.js:37:14)
13:34:43.679 [pimatic] error:>    at null.RetrySend._bOff [as _onTimeout] (/home/pi/pimatic-app/node_modules/pimatic-tradfri/node_modules/tradfri-coapdtls/lib/retry_send.js:29:10)
13:34:43.679 [pimatic] error:>    at Timer.listOnTimeout (timers.js:92:15)
13:34:43.679 [pimatic] error:> This is most probably a bug in pimatic or in a module, please report it!
13:34:43.682 [pimatic] info: exiting...

**Comment by treban** [comment]
Update 0.1.11 should fix the exception errors.

**Comment by scobby** [comment]
great, i will test that.

**Comment by treban** [comment]
Problem Fixed: ...
https://forum.pimatic.org/topic/3075/new-pimatic-tradfri-plugin-ikea-smart-lights/47

**Comment by treban** [comment]
If the error occurs again, I re-open the ticket again.
